sudo: false

branches:
only:
  - master

env:
  global:
    - BINSTAR_USER: kelvinrr
  matrix:
    - PYTHON_VERSION: 3.5

os:
  - linux
  - osx

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      if [ "$PYTHON_VERSION" == 2.7 ]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    else
      if ["$PYTHON_VERSION" == 2.7]; then
        curl -o miniconda.sh  https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh;
      else
        curl -o miniconda.sh  https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
      fi
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Install dependencies
  - conda config --add channels conda-forge
  - conda config --add channels menpo
  - conda config --add channels jlaura
  - conda config --add channels kelvinrr
  - conda config --set ssl_verify false
  - conda install python=$PYTHON_VERSION
  - conda install -c conda-forge numpy
  - conda install -c jlaura plio opencv3=3.0.0
  - conda install -c conda-forge vlfeat
  - conda install -c menpo cyvlfeat
  - pip install pillow pysal
  - conda install scipy networkx numexpr dill cython pyyaml matplotlib pymongo

  # Development installation
  - conda install pytest pytest-cov coverage sh anaconda-client
  - pip install coveralls

    # Straight from the menpo team
  - if [["$TRAVIS_OS_NAME" == "osx"]]; then
      curl -o condaci.py https://raw.githubusercontent.com/menpo/condaci/v0.4.8/condaci.py;
    else
      wget https://raw.githubusercontent.com/menpo/condaci/v0.4.8/condaci.py -O condaci.py;
    fi
    # Build autocnet and push to anaconda cloud
  - python condaci.py setup

script:
  - pytest
  # clean up any remaining processes...
  - if [ $TRAVIS_OS_NAME == "linux" ]; then killall5; fi

after_success:
  # Upload to anaconda and push to coveralls
  - ~/miniconda/bin/python condaci.py build ./conda
  - coveralls

# notifications:
#   webhooks:
#     on_success: always
#     on_failure: always
